<?php

return [
    'ddc_edition' => '23',
    'ddc_rules' => [
        'validation_mode' => 'warn',
    ],
    'online_detection_mode' => 'strict',
    'relators' => [
        'terms' => [
            'author', 'editor', 'illustrator', 'translator', 'photographer',
            'composer', 'director', 'narrator', 'contributor', 'compiler',
            'publisher', 'adapter', 'creator', 'performer', 'actor',
            'producer', 'arranger', 'designer', 'cover designer', 'reviewer',
            'researcher', 'meeting',
            'pengarang', 'penulis', 'penyunting', 'ilustrator', 'penerjemah',
            'fotografer', 'komposer', 'sutradara', 'narator', 'kontributor',
            'penyusun', 'penerbit', 'penyadur', 'pencipta', 'penyaji', 'aktor',
            'produser', 'penata musik', 'desainer', 'ilustrator sampul',
            'pengulas', 'penata letak', 'penata grafis', 'penyunting bahasa',
            'editor bahasa', 'peneliti', 'seminar', 'konferensi', 'kongres',
            'symposium', 'simposium', 'meeting',
        ],
        'codes' => [
            'aut', 'edt', 'ill', 'trl', 'pht', 'cmp', 'drt', 'nrt', 'ctb', 'com',
            'pbl', 'adp', 'cre', 'prf', 'act', 'pro', 'arr', 'dsr', 'cov', 'rev',
            'res', 'mtg',
        ],
    ],
    'rda_34x' => [
        'audio' => [
            '347' => [
                ['a' => 'audio file', '2' => 'rda'],
            ],
        ],
        'video' => [
            '347' => [
                ['a' => 'video file', '2' => 'rda'],
            ],
        ],
        'text' => [
            '347' => [
                ['a' => 'text file', '2' => 'rda'],
            ],
        ],
    ],
    'serial_frequency_codes' => [
        'daily' => 'd',
        'harian' => 'd',
        'weekly' => 'w',
        'mingguan' => 'w',
        'biweekly' => 'e',
        'dwimingguan' => 'e',
        'semimonthly' => 's',
        'setengah bulanan' => 's',
        'monthly' => 'm',
        'bulanan' => 'm',
        'bimonthly' => 'b',
        'dwibulanan' => 'b',
        'quarterly' => 'q',
        'triwulanan' => 'q',
        'three times a year' => 't',
        'tiga kali setahun' => 't',
        'semiannual' => 'f',
        'semesteran' => 'f',
        'annual' => 'a',
        'tahunan' => 'a',
        'biennial' => 'g',
        'dua tahunan' => 'g',
        'triennial' => 'h',
        'tiga tahunan' => 'h',
        'continuous' => 'k',
        'continuously updated' => 'k',
    ],
    'serial_type_codes' => [
        'n' => ['newspaper', 'koran'],
        'p' => ['journal', 'jurnal', 'magazine', 'periodical', 'majalah'],
        'm' => ['series', 'seri'],
        'd' => ['database'],
        'w' => ['website', 'web'],
        'l' => ['loose-leaf', 'looseleaf'],
    ],
    'serial_type_overrides' => [
        'newspaper' => 'n',
        'koran' => 'n',
        'database' => 'd',
        'web' => 'w',
        'website' => 'w',
        'magazine' => 'p',
        'majalah' => 'p',
        'journal' => 'p',
        'jurnal' => 'p',
    ],
    'serial_form_of_item_map' => [
        'web' => 'o',
        'website' => 'o',
        'online' => 'o',
        'database' => 'o',
    ],
    'authority_dedup_strict' => false,
    'policy_packs' => [
        'rda_core' => [
            'name' => 'RDA Core',
            'rules' => [
                'relator_uncontrolled' => 'warn',
                'audio_missing_narrator' => 'warn',
                'ddc_missing_call_number' => 'warn',
                'serial_frequency_missing' => 'warn',
                'serial_008_missing' => 'warn',
                'serial_008_detail_missing' => 'warn',
                'serial_362_missing' => 'warn',
                'serial_588_missing' => 'warn',
                'subject_scheme_unknown' => 'warn',
                'title_leading_punctuation' => 'warn',
                'name_date_format' => 'warn',
                'relator_missing' => 'warn',
                'authority_missing' => 'warn',
                'authority_uri_missing' => 'warn',
                'authority_dedup' => 'warn',
                'control_field_mismatch' => 'warn',
                'publisher_missing' => 'error',
                'material_type_missing' => 'error',
                'media_type_missing' => 'error',
                'physical_desc_missing' => 'warn',
                'call_number_missing' => 'warn',
                'isbn_invalid' => 'error',
                'issn_invalid' => 'error',
            ],
        ],
    ],
    'policy_rule_keys' => [
        'relator_uncontrolled',
        'audio_missing_narrator',
        'ddc_missing_call_number',
        'serial_frequency_missing',
        'serial_008_missing',
        'serial_008_detail_missing',
        'serial_362_missing',
        'serial_588_missing',
        'subject_scheme_unknown',
        'title_leading_punctuation',
        'name_date_format',
        'relator_missing',
        'authority_missing',
        'authority_uri_missing',
        'authority_dedup',
        'control_field_mismatch',
        'publisher_missing',
        'material_type_missing',
        'media_type_missing',
        'physical_desc_missing',
        'call_number_missing',
        'isbn_invalid',
        'issn_invalid',
    ],
    'policy_schema_version' => 3,
    'subject_schemes' => ['local', 'lcsh'],
    'include_holdings_fields' => true,
    'authority_source_priority' => ['lcnaf', 'viaf', 'isni', 'wikidata', 'uri'],
    'authority_uri_map' => [
        'lcnaf' => 'http://id.loc.gov/authorities/names/{id}',
        'viaf' => 'https://viaf.org/viaf/{id}',
        'isni' => 'https://isni.org/isni/{id}',
        'wikidata' => 'https://www.wikidata.org/entity/{id}',
    ],
    'place_codes' => [
        'strict_country_codes' => false,
        'city' => [
            // Indonesia
            'jakarta' => 'io',
            'bandung' => 'io',
            'surabaya' => 'io',
            'yogyakarta' => 'io',
            'yogya' => 'io',
            'medan' => 'io',
            'makassar' => 'io',
            'semarang' => 'io',
            'palembang' => 'io',
            'denpasar' => 'io',
            'malang' => 'io',
            'padang' => 'io',
            'batam' => 'io',
            'pontianak' => 'io',
            'banjarmasin' => 'io',
            'manado' => 'io',
            'pekanbaru' => 'io',
            'samarinda' => 'io',
            'balikpapan' => 'io',
            // UK
            'london' => 'xxk',
            'manchester' => 'xxk',
            'birmingham' => 'xxk',
            'glasgow' => 'xxk',
            'edinburgh' => 'xxk',
            'cardiff' => 'xxk',
            'belfast' => 'xxk',
            // USA
            'new york' => 'xxu',
            'los angeles' => 'xxu',
            'chicago' => 'xxu',
            'washington' => 'xxu',
            'boston' => 'xxu',
            'san francisco' => 'xxu',
            // Australia
            'sydney' => 'at',
            'melbourne' => 'at',
            'brisbane' => 'at',
            'perth' => 'at',
            'adelaide' => 'at',
            // Japan
            'tokyo' => 'ja',
            'osaka' => 'ja',
            'kyoto' => 'ja',
            // China
            'beijing' => 'cc',
            'shanghai' => 'cc',
            // Singapore
            'singapore' => 'si',
            // Malaysia
            'kuala lumpur' => 'my',
            // Thailand
            'bangkok' => 'th',
            // Vietnam
            'hanoi' => 'vm',
            'ho chi minh' => 'vm',
            // Philippines
            'manila' => 'ph',
        ],
        'country' => [
            // Asia
            'indonesia' => 'io',
            'republic of indonesia' => 'io',
            'ri' => 'io',
            'malaysia' => 'my',
            'singapore' => 'si',
            'thailand' => 'th',
            'vietnam' => 'vm',
            'philippines' => 'ph',
            'japan' => 'ja',
            'korea' => 'ko',
            'south korea' => 'ko',
            'north korea' => 'kn',
            'china' => 'cc',
            'taiwan' => 'ch',
            'hong kong' => 'cc',
            'india' => 'ii',
            'pakistan' => 'pk',
            'saudi arabia' => 'su',
            'united arab emirates' => 'ts',
            'uae' => 'ts',
            'turkey' => 'tu',
            'iran' => 'ir',
            'iraq' => 'iq',
            'qatar' => 'qa',
            'oman' => 'mk',
            'kuwait' => 'ku',
            'israel' => 'is',
            'sri lanka' => 'ce',
            'nepal' => 'np',
            'bangladesh' => 'bg',
            // Europe
            'united kingdom' => 'xxk',
            'uk' => 'xxk',
            'great britain' => 'xxk',
            'england' => 'xxk',
            'scotland' => 'xxk',
            'wales' => 'xxk',
            'northern ireland' => 'xxk',
            'ireland' => 'ie',
            'france' => 'fr',
            'germany' => 'gw',
            'netherlands' => 'ne',
            'belgium' => 'be',
            'spain' => 'sp',
            'italy' => 'it',
            'portugal' => 'po',
            'switzerland' => 'sz',
            'sweden' => 'sw',
            'norway' => 'no',
            'denmark' => 'dk',
            'finland' => 'fi',
            'austria' => 'au',
            'poland' => 'pl',
            'romania' => 'rm',
            'greece' => 'gr',
            'russia' => 'ru',
            'ukraine' => 'un',
            'czech republic' => 'xr',
            'slovakia' => 'xo',
            'slovenia' => 'xv',
            'croatia' => 'ci',
            'bulgaria' => 'bu',
            'hungary' => 'hu',
            // North America
            'united states' => 'xxu',
            'usa' => 'xxu',
            'u s a' => 'xxu',
            'us' => 'xxu',
            'canada' => 'xxc',
            'mexico' => 'mx',
            // South America
            'brazil' => 'bl',
            'argentina' => 'ag',
            'chile' => 'cl',
            'colombia' => 'ck',
            'peru' => 'pe',
            'ecuador' => 'ec',
            'uruguay' => 'uy',
            'paraguay' => 'py',
            'bolivia' => 'bo',
            'venezuela' => 've',
            // Africa
            'south africa' => 'sa',
            'nigeria' => 'nr',
            'kenya' => 'ke',
            'egypt' => 'ua',
            'morocco' => 'mr',
            'algeria' => 'ae',
            'tunisia' => 'ti',
            'ghana' => 'gh',
            'ethiopia' => 'et',
            // Oceania
            'australia' => 'at',
            'new zealand' => 'nz',
            'papua new guinea' => 'pp',
        ],
    ],
    'media_profiles' => [
        [
            'name' => 'video',
            'keywords' => ['video', 'dvd', 'vcd', 'blu-ray', 'bluray', 'film'],
            'type_006' => 'g',
            'type_007' => 'vd',
            'pattern_006' => 'g                 ',
            'pattern_007' => 'vd cvaizq',
            'min_007' => 7,
            'pattern_008_visual' => '{entered}{status}{date1}{date2}{place}                {lang}  ',
            'rda_336' => ['a' => 'two-dimensional moving image', 'b' => 'tdi', '2' => 'rdacontent'],
            'rda_337' => ['a' => 'video', 'b' => 'v', '2' => 'rdamedia'],
            'rda_338' => ['a' => 'videodisc', 'b' => 'vd', '2' => 'rdacarrier'],
            'rda_337_online' => ['a' => 'computer', 'b' => 'c', '2' => 'rdamedia'],
            'rda_338_online' => ['a' => 'online resource', 'b' => 'cr', '2' => 'rdacarrier'],
        ],
        [
            'name' => 'audio_music',
            'keywords' => ['musik', 'music', 'album', 'song'],
            'type_006' => 'j',
            'type_007' => 'sd',
            'pattern_006' => 'j                 ',
            'pattern_007' => 'sd fmnngnn',
            'min_007' => 7,
            'pattern_008_music' => '{entered}{status}{date1}{date2}{place}                {lang}  ',
            'rda_336' => ['a' => 'performed music', 'b' => 'prm', '2' => 'rdacontent'],
            'rda_337' => ['a' => 'audio', 'b' => 's', '2' => 'rdamedia'],
            'rda_338' => ['a' => 'audio disc', 'b' => 'sd', '2' => 'rdacarrier'],
            'rda_337_online' => ['a' => 'computer', 'b' => 'c', '2' => 'rdamedia'],
            'rda_338_online' => ['a' => 'online resource', 'b' => 'cr', '2' => 'rdacarrier'],
        ],
        [
            'name' => 'audio',
            'keywords' => ['audio', 'sound', 'mp3', 'cd audio', 'cassette'],
            'type_006' => 'i',
            'type_007' => 'sd',
            'pattern_006' => 'i                 ',
            'pattern_007' => 'sd fmnngnn',
            'min_007' => 7,
            'pattern_008_audio' => '{entered}{status}{date1}{date2}{place}                {lang}  ',
            'rda_336' => ['a' => 'spoken word', 'b' => 'spw', '2' => 'rdacontent'],
            'rda_337' => ['a' => 'audio', 'b' => 's', '2' => 'rdamedia'],
            'rda_338' => ['a' => 'audio disc', 'b' => 'sd', '2' => 'rdacarrier'],
            'rda_337_online' => ['a' => 'computer', 'b' => 'c', '2' => 'rdamedia'],
            'rda_338_online' => ['a' => 'online resource', 'b' => 'cr', '2' => 'rdacarrier'],
        ],
        [
            'name' => 'electronic',
            'keywords' => ['ebook', 'e-book', 'digital', 'online', 'komputer', 'computer', 'file', 'pdf', 'epub'],
            'type_006' => 'm',
            'type_007' => 'cr',
            'pattern_006' => 'm                 ',
            'pattern_007' => 'cr cnuuu',
            'min_007' => 6,
            'pattern_008_cf' => '{entered}{status}{date1}{date2}{place}                {lang}  ',
            'form_of_item' => 'o',
            'rda_336' => ['a' => 'text', 'b' => 'txt', '2' => 'rdacontent'],
            'rda_337' => ['a' => 'computer', 'b' => 'c', '2' => 'rdamedia'],
            'rda_338' => ['a' => 'online resource', 'b' => 'cr', '2' => 'rdacarrier'],
        ],
        [
            'name' => 'map',
            'keywords' => ['peta', 'map', 'atlas', 'kartografi'],
            'type_006' => 'e',
            'type_007' => 'aj',
            'pattern_006' => 'e                 ',
            'pattern_007' => 'aj czn',
            'min_007' => 5,
            'pattern_008_map' => '{entered}{status}{date1}{date2}{place}                {lang}  ',
            'rda_336' => ['a' => 'cartographic image', 'b' => 'cri', '2' => 'rdacontent'],
            'rda_337' => ['a' => 'unmediated', 'b' => 'n', '2' => 'rdamedia'],
            'rda_338' => ['a' => 'sheet', 'b' => 'nb', '2' => 'rdacarrier'],
            'rda_337_online' => ['a' => 'computer', 'b' => 'c', '2' => 'rdamedia'],
            'rda_338_online' => ['a' => 'online resource', 'b' => 'cr', '2' => 'rdacarrier'],
        ],
        [
            'name' => 'text',
            'keywords' => ['buku', 'book', 'teks', 'text', 'cetak', 'print', 'majalah', 'journal', 'jurnal', 'serial', 'koran', 'newspaper'],
            'type_006' => 'a',
            'type_007' => 'ta',
            'pattern_006' => 'a                 ',
            'pattern_007' => 'ta',
            'min_007' => 2,
            'pattern_008_books' => '{entered}{status}{date1}{date2}{place}                {lang}  ',
            'rda_336' => ['a' => 'text', 'b' => 'txt', '2' => 'rdacontent'],
            'rda_337' => ['a' => 'unmediated', 'b' => 'n', '2' => 'rdamedia'],
            'rda_338' => ['a' => 'volume', 'b' => 'nc', '2' => 'rdacarrier'],
            'rda_337_online' => ['a' => 'computer', 'b' => 'c', '2' => 'rdamedia'],
            'rda_338_online' => ['a' => 'online resource', 'b' => 'cr', '2' => 'rdacarrier'],
        ],
    ],
];
